Be extremely aggressive about dependency resolution
This switches the R2 modules to using very specific commits that are
known to work together, and upgrades to Kotlin 1.4.31.

The resolutionStrategy.force method is used to force both Kotlin
and R2 to a consistent version. This fixes errors such as these
when attempting to open a book:

```
Caused by: java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/Integer;[Ljava/lang/Object;Ljava/lang/Throwable;)V in class Lorg/readium/r2/shared/UserException; or its super classes (declaration of 'org.readium.r2.shared.UserException' appears in /data/app/org.thepalaceproject.palace-WVAHEL6gOM25JwkPb24KAQ==/base.apk!classes4.dex)
        at org.readium.r2.lcp.license.container.ZIPLicenseContainer.read(ZIPLicenseContainer.kt:40)
```